apiVersion: batch/v1
kind: Job
metadata:
  name: map_matcher_job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: app
          image: flowlabs-mapper_service:latest
          env:
            - name: POSTGRES_URL
            - name: PULSAR_BROKER
